name: ai_requirements
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - openai
      - pycomfort
      - crewai
      - 'crewai[tools]'
      - langchain>=0.1.16
      - langchain_openai
      - langchain-community>=0.0.33
      - requests
      - xmltodict