name: ai_requirements
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - openai
      - anthropic
      - pycomfort
      - crewai>=0.28.8
      - 'crewai[tools]'
      - gptcache
      - langchain>=0.1.16
      - langchain_openai
      - langchain-community>=0.0.33
      - langchain-anthropic>=0.1.11
      - langchain-openai
      - langchain-experimental
      - requests
      - xmltodict
      - polars
      - langchain-groq
      - click